[package]
name = "stroke-width-transform-rs"
version = "0.1.0"
edition = "2021"

[[example]]
name = "swt"
crate-type = ["bin"]

[dependencies]
image = "0.24.6"
num-traits = "0.2.15"
imageproc = "0.23.0"

[dev-dependencies]
clap = "4.2.1"
show-image = { version = "0.13.1", features = [ "image" ] }
